# 🐛 bug - 버그 수정 관련
🐛 bug:
  - title: ["^fix:", '^fix\(', "^🐛"]

# ✨ feature - 새로운 기능
✨ feature:
  - title: ["^feat:", '^feat\(', "^✨"]

# 📚 docs - 문서 변경
📚 docs:
  - title: ["^docs:", '^docs\(', "^📚"]

# 💄 style - 코드 스타일 변경
💄 style:
  - title: ["^style:", '^style\(', "^💄"]

# ♻️ refactor - 리팩토링
♻️ refactor:
  - title: ["^refactor:", '^refactor\(', "^♻️"]

# 🧪 test - 테스트 추가/수정
🧪 test:
  - title: ["^test:", '^test\(', "^🧪"]

# 🔧 chore - 빌드 프로세스, 도구 설정 등
🔧 chore:
  - title: ["^chore:", '^chore\(', "^🔧"]

# ⚡ perf - 성능 개선
⚡ perf:
  - title: ["^perf:", '^perf\(', "^⚡"]

# 👷 ci - CI 설정 변경
👷 ci:
  - title: ["^ci:", '^ci\(', "^👷"]

# 📦 build - 빌드 시스템 변경
📦 build:
  - title: ["^build:", '^build\(', "^📦"]

# ⏪ revert - 이전 커밋 되돌리기
⏪ revert:
  - title: ["^revert:", '^revert\(', "^⏪", "^Revert"]
