name: "YAPP-Web-Team-1-FE 이슈 생성"
description: "YAPP-Web-Team-1-FE Front Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다."
labels: [order]
title: "이슈 이름을 작성해주세요"
body:
  - type: input
    id: parentKey
    attributes:
      label: "🏷️ 상위 작업 (Ticket Number)"
      description: "상위 작업의 Ticket Number를 기입해주세요"
      placeholder: "PRODUCT-00"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "🚀 구현 내용"
      description: "이슈에 대해서 자세히 설명해주세요"
      value: |
        - About Details
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "✅ 할 일"
      description: "해당 이슈에 대해 필요한 작업목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
