import type { Metadata } from "next";

import { MSWProvider } from "@/providers/MSWProvider";
import QueryProvider from "@/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (process.env.NEXT_RUNTIME === "nodejs") {
  const { server } = await import("@/mocks/server");
  console.info("🔥 [MSW] Server-side mocking enabled");
  server.listen();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <QueryProvider>
          <MSWProvider>{children}</MSWProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
