import "@/styles/reset.css";
import "@/styles/globals.css";

import type { Metadata } from "next";

import { RegisterServiceWorkerClient } from "@/lib/pwa";
import { MSWProvider, QueryProvider } from "@/providers";
import { pretendard } from "@/styles/pretendard";

export const metadata: Metadata = {
  title: "Eat-da",
  description: "Generated by create next app",
};

if (process.env.NEXT_RUNTIME === "nodejs") {
  const { server } = await import("@/mocks/server");
  console.info("🔥 [MSW] Server-side mocking enabled");
  server.listen();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={pretendard.className}>
      <body>
        <RegisterServiceWorkerClient />
        <QueryProvider>
          <MSWProvider>{children}</MSWProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
